# Generated by Django 4.0.6 on 2022-07-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_app', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='сюда имя писать надо, максимум 64 символа', max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='test_app.person', verbose_name='хозяин')),
            ],
            options={
                'verbose_name': 'петомец',
                'verbose_name_plural': 'петомцы',
                'ordering': ['owner'],
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
