# Generated by Django 4.0.6 on 2022-07-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип петомца',
                'verbose_name_plural': 'типы петомцев',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'человек', 'verbose_name_plural': 'люди'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['owner_id', 'name'], 'verbose_name': 'петомец', 'verbose_name_plural': 'петомцы'},
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(help_text='сюда адресс писать надо, максимум 64 символа', max_length=64, unique=True, verbose_name='адресс')),
                ('persons', models.ManyToManyField(related_name='houses', to='test_app.person')),
                ('pets', models.ManyToManyField(related_name='houses', to='test_app.pet')),
            ],
            options={
                'verbose_name': 'дом',
                'verbose_name_plural': 'дома',
                'ordering': ['adress'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='test_app.pettype', verbose_name='тип'),
        ),
    ]
